update chinese tra
yaap/packages_apps_YASP pull request #9
Opened 2020-12-31 07:15 UTC by ZONGQUAN-HU

2021-01-01 12:41 UTC, ALKALiKong233 commented
It's a mess again 😂 Let's clean up

2021-01-01 14:24 UTC, ALKALiKong233 approved these changes
It's okay now 👌

2021-01-06 13:59 UTC, idoybh requested changes

2021-01-06 13:59 UTC, idoybh commented on res/values-zh-rCN/yaap_strings.xml
>      <!-- Incall vibrate options -->
```suggestion
    <!-- Incall vibrate options -->
```

2021-01-06 14:00 UTC, idoybh approved these changes

2021-01-06 14:00 UTC, merged